[package]
name = "vibecode-rs"
version = "1.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enigo = "0.5.0"

[profile.release]
strip = true
